packages:
- apps/*
- packages/*
catalog:
  '@tailwindcss/aspect-ratio': ^0.4.2
  '@tailwindcss/forms': ^0.5.9
  '@vueuse/core': ^13.2.0
  '@vueuse/components': ^13.5.0
  '@vueuse/integrations': ^13.5.0
  typescript: ^5.8.3
  vue: ^3.5.15
  vue-tsc: ^3.0.4
  tailwindcss: ^3.4.17
  focus-trap: ^7.5.4
  fast-deep-equal: ^3.1.3
  tailwind-scrollbar-hide: ^2.0.0
