packages:
- apps/*
- packages/*
catalog:
  '@aminnausin/cedar-ui': ^0.0.13
  '@tailwindcss/aspect-ratio': ^0.4.2
  '@tailwindcss/forms': ^0.5.10
  '@vueuse/core': ^13.6.0
  '@vueuse/components': ^13.6.0
  '@vueuse/integrations': ^13.6.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  typescript: ^5.9.2
  vue: ^3.5.18
  vue-tsc: ^3.0.5
  tailwindcss: ^4.1.17
  focus-trap: ^7.6.5
  fast-deep-equal: ^3.1.3
  tailwind-scrollbar-hide: ^2.0.0
  reka-ui: ^2.4.1

overrides:
  '@aminnausin/cedar-ui': 'link:'
